routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return redirect('/login');
});

Auth::routes();

Route::get('/dashboard', 'HomeController@index')->name('dashboard');
Route::get('kelas/{kelas:slug}/home', 'HomeController@home')->name('home');

Route::group(['middleware' => 'auth'], function () {
    Route::resource('users', 'UserController');
    Route::resource('kelas.materi', 'MateriController')->parameters([
        'kelas' => 'kelas:slug',
    ]);
    Route::resource('kelas.video', 'VideoController')->parameters([
        'kelas' => 'kelas:slug',
    ]);
    Route::post('kelas/{kelas:slug}/task/{id}/submit', 'TaskController@submit')->name('task.submit');
    Route::resource('kelas.task', 'TaskController')->parameters([
        'kelas' => 'kelas:slug',
    ]);
    Route::get('kelas/{kelas:slug}/people', 'KelasController@people')->name('kelas.people');
    Route::get('kelas/{kelas:slug}/diskusi', 'KelasController@diskusi')->name('kelas.diskusi');
    Route::get('kelas/join/create', 'KelasController@cjoin')->name('join.create');
    Route::post('kelas/join', 'KelasController@join')->name('join.store');
    Route::resource('kelas', 'KelasController')->parameters([
        'kelas' => 'kelas:slug',
    ]);
    Route::get('kelas/{kelas:slug}/soal/{id}/essayshow', 'SoalController@essay')->name('soal.showEssay');
    Route::post('kelas/{kelas:slug}/soal/exam/answer', 'SoalController@storeAnswer')->name('soal.storeAnswer');
    Route::post('kelas/{kelas:slug}/soal/exam/finish', 'SoalController@examFinish')->name('soal.examFinish');
    Route::post('kelas/{kelas:slug}/soal/{id}/item', 'SoalController@storeItem')->name('soal.storeItem');
    Route::post('kelas/{kelas:slug}/soal/{id}/exam', 'SoalController@examStart')->name('soal.examStart');
    Route::resource('kelas.soal', 'SoalController')->parameters([
        'kelas' => 'kelas:slug',
    ]);
    Route::get('home/notifications', 'HomeController@loadMoreNotifications');
    Route::post('kelas/{kelas:slug}/home/feed', 'HomeController@feed')->name('home.feed');
    Route::post('kelas/{kelas:slug}/home/reply', 'HomeController@reply')->name('home.reply');

    Route::get('kelas/{kelas:slug}/activity', 'ReportController@activity')->name('report.activity');
    Route::post('kelas/{kelas:slug}/nilai', 'ReportController@saveNilai')->name('report.saveNilai');
    Route::get('kelas/{kelas:slug}/nilai', 'ReportController@nilai')->name('report.nilai');
    Route::get('kelas/{kelas:slug}/nilai/{id}', 'ReportController@nilaiDetail')->name('report.nilaiDetail');

    Route::get('setting', 'HomeController@setting')->name('home.setting');
    Route::post('setting', 'HomeController@updateSetting')->name('home.updateSetting');
    Route::post('password', 'HomeController@updatePassword')->name('home.updatePassword');
});

app/Video.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Video extends Model
{
    protected $guarded = ['id'];

    public function kelas()
    {
        return $this->belongsTo(Kelas::class);
    }
}

app/Http/Controllers/VideoController.php
<?php

namespace App\Http\Controllers;

use App\Kelas;
use App\Video;

use Illuminate\Http\Request;

class VideoController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Kelas $kelas)
    {
        $data = Video::where('kelas_id', '=', $kelas->id)->get();
        return view('video.index', compact('data', 'kelas'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create(Kelas $kelas)
    {
        return view('video.create', compact('kelas'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request, Kelas $kelas)
    {
        $input = $request->all();

        if ($request->hasFile('file')) {
            $input['file'] = time().'_'.request()->file->getClientOriginalName();
            
            request()->file->move(public_path('uploads/file/'), $input['file']);
        }
        
        $data = Video::create($input);

        activity()
            ->performedOn($data)
            ->causedBy(auth()->user())
            ->withProperties(['kelas' => $kelas->id])
            ->log(':causer.name menambahkan video :subject.name');

        flash('Berhasil menambahkan video')->success();

        return redirect()->route('kelas.video.index', [$kelas->slug]);
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show(Kelas $kelas, $id)
    {
        try {
            $data = Video::find($id);

            activity()
                ->performedOn($data)
                ->causedBy(auth()->user())
                ->withProperties(['kelas' => $kelas->id])
                ->log(':causer.name telah menonton video :subject.name hingga selesai');

            return response()->json([
                'status' => true,
                'message' => 'Berhasil menyelesaikan video'
            ]);
        } catch(\Exception $e) {
            return response()->json([
                'status' => false,
                'message' => 'Gagal menyelesaikan video'
            ]);
        }
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(Kelas $kelas, $id)
    {
        $data = Video::find($id);
        return view('video.edit', compact('data', 'kelas'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Kelas $kelas, $id)
    {
        $input = $request->all();

        if ($request->hasFile('file')) {
            $input['file'] = time().'_'.request()->file->getClientOriginalName();
            
            request()->file->move(public_path('uploads/file/'), $input['file']);
        }
        
        Video::find($id)->update($input);

        flash('Berhasil mengedit video')->success();

        return redirect()->route('kelas.video.index', [$kelas->slug]);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(Kelas $kelas, $id)
    {
        try {
            Video::find($id)->delete();

            return response()->json([
                'status' => true,
                'message' => 'Berhasil menghapus video'
            ]);
        } catch(\Exception $e) {
            return response()->json([
                'status' => false,
                'message' => 'Gagal menghapus video'
            ]);
        }
    }
}

resources/views/video/create.blade.php
<div class="modal-dialog" role="document">
    {!! Form::open(['url' => route('kelas.video.store', [$kelas->slug]), 'method' => 'post', 'files' => true]) !!}
    <div class="modal-content">
        <div class="modal-header">
            <h4 class="modal-title" id="exampleModalLabel">Tambah Video</h5>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
            </button>
        </div>
        <div class="modal-body">
            <input type="hidden" name="kelas_id" value="{{ $kelas->id }}">
            <div class="form-group">
                {!! Form::label('name', 'Judul') !!}
                {!! Form::text('name', null, ['class' => 'form-control', 'required', 'oninvalid' => "this.setCustomValidity('Mohon diisi dengan lengkap')", 'oninput' => "this.setCustomValidity('')"]) !!}
            </div>
            <div class="form-group">
                {!! Form::label('description', 'Deskripsi') !!}
                {!! Form::textarea('description', null, ['class' => 'form-control', 'required', 'oninvalid' => "this.setCustomValidity('Mohon diisi dengan lengkap')", 'oninput' => "this.setCustomValidity('')"]) !!}
            </div>
            <div class="form-group">
                {!! Form::label('file', 'File') !!}
                {!! Form::file('file', null, ['class' => 'form-control-file', 'required', 'oninvalid' => "this.setCustomValidity('Mohon diisi dengan lengkap')", 'oninput' => "this.setCustomValidity('')"]) !!}
            </div>
        </div>
        <div class="modal-footer">
            <button type="submit" class="btn btn-primary">Simpan</button>
        </div>
    </div>
    {!! Form::close() !!}
</div>

resources/views/video/edit.blade.php
<div class="modal-dialog" role="document">
    {!! Form::open(['url' => route('kelas.video.update', [$kelas->slug, $data->id]), 'method' => 'post', 'files' => true]) !!}
    @method('PUT')
    <div class="modal-content">
        <div class="modal-header">
            <h4 class="modal-title" id="exampleModalLabel">Edit Materi</h5>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
            </button>
        </div>
        <div class="modal-body">
            <div class="form-group">
                {!! Form::label('name', 'Judul') !!}
                {!! Form::text('name', $data->name, ['class' => 'form-control', 'required', 'oninvalid' => "this.setCustomValidity('Mohon diisi dengan lengkap')", 'oninput' => "this.setCustomValidity('')"]) !!}
            </div>
            <div class="form-group">
                {!! Form::label('description', 'Deskripsi') !!}
                {!! Form::textarea('description', $data->description, ['class' => 'form-control', 'required', 'oninvalid' => "this.setCustomValidity('Mohon diisi dengan lengkap')", 'oninput' => "this.setCustomValidity('')"]) !!}
            </div>
            <div class="form-group">
                {!! Form::label('file', 'File') !!}
                {!! Form::file('file', null, ['class' => 'form-control-file', 'required', 'oninvalid' => "this.setCustomValidity('Mohon diisi dengan lengkap')", 'oninput' => "this.setCustomValidity('')"]) !!}
            </div>
        </div>
        <div class="modal-footer">
            <button type="submit" class="btn btn-primary">Simpan</button>
        </div>
    </div>
    {!! Form::close() !!}
</div>

resources/views/video/index.blade.php
@extends('layouts.app2')

@section('header')
    @include('kelas.partials.header')
@endsection

@section('content')
<div class="sidebar-left">
    <div class="sidebar">
        <div class="sidebar-content card">
            @if (!auth()->user()->hasRole('student'))
                <div class="chat-fixed-search">
                    <div class="d-flex justify-content-center">
                        <div class="position-relative">
                            <button class="btn btn-primary round action_add" data-href="{{ route('kelas.video.create', [$kelas->slug]) }}">Tambah Video</button>
                        </div>
                    </div>
                </div>
            @endif
            <div id="users-list" class="chat-user-list list-group position-relative">
                <h3 class="primary p-1 mb-0">Timeline Video</h3>
                <ul class="chat-users-list-wrapper media-list">
                    @if (count($data) > 0)
                    @foreach ($data as $value)
                    <li data-v-url="{{ asset('uploads/file/'.$value->file) }}" data-v-id="{{ $value->id }}">
                        <div class="pr-1">
                            <span class="avatar m-0 avatar-md"><img class="media-object rounded-circle" src="{{ asset('assets/images/playbutton.png') }}" height="42" width="42" alt="PlayButton">
                                <i></i>
                            </span>
                        </div>
                        <div class="user-chat-info">
                            <div class="contact-info">
                                <h5 class="font-weight-bold mb-0">{{ $value->name ?? '' }}</h5>
                                <p class="truncate">{{ $value->description ?? '' }}</p>
                            </div>
                            <div class="contact-meta">
                                <span class="float-right">{{ date('Y/m/d', strtotime($value->created_at)) }}</span><br>
                                <span class="action-edit float-right" data-href="{{ route('kelas.video.edit', [$kelas->slug, $value->id]) }}"><i class="feather icon-edit" title="Edit"></i></span>
                                <span class="action-delete float-right" data-href="{{ route('kelas.video.destroy', [$kelas->slug, $value->id]) }}"><i class="feather icon-trash" title="Delete"></i></span>
                            </div>
                        </div>
                    </li>
                    @endforeach
                    @else
                        <div class="row d-flex justify-content-center mb-1">
                            <img src="{{ asset('app-assets/images/pages/graphic-6.png') }}" alt="" width="150" height="150">
                        </div>
                        <h3 class="row d-flex justify-content-center">Tidak ada video</h3>
                        <p class="row d-flex justify-content-center">Data video akan ditampilkan disini</p>
                    @endif
                </ul>
            </div>
        </div>
        <!--/ Chat Sidebar area -->

    </div>
</div>
<div class="content-right">
    <div class="content-wrapper">
        <div class="content-header row">
        </div>
        <div class="content-body">
            <div class="chat-overlay"></div>
            <section class="chat-app-window">
                <div class="start-chat-area">
                    <span class="mb-1 start-chat-icon feather icon-play-circle"></span>
                    <h4 class="py-50 px-1 sidebar-toggle start-chat-text">Mulai Menonton</h4>
                </div>
                <div class="active-chat d-none">
                    <div class="chat_navbar">
                        <header class="chat_header d-flex justify-content-between align-items-center p-1">
                            <div class="vs-con-items d-flex align-items-center">
                                <div class="sidebar-toggle d-block d-lg-none mr-1"><i class="feather icon-menu font-large-1"></i></div>
                                <div class="avatar user-profile-toggle m-0 m-0 mr-1">
                                    <img src="{{ asset('assets/images/playbutton.png') }}" alt="" height="40" width="40" />
                                    <span class="avatar-status-busy"></span>
                                </div>
                                <h6 class="mb-0">Video</h6>
                            </div>
                        </header>
                    </div>
                    <div class="video-container">
                        
                    </div>
                </div>
            </section>
        </div>
    </div>
</div>

<div class="modal fade action-modal" id="xlarge" tabindex="-1" role="dialog" aria-labelledby="myModalLabel16" aria-hidden="true"></div>

@endsection

@section('js')
    <script src="{{ asset('app-assets/js/scripts/pages/app-chat.js') }}"></script>

    <script>
        $('.action_add').on('click', function(e){
            var t = $('.action-modal');
            $.ajax({
                url: $(this).data('href'),
                dataType: "html",
                success: function(e) {
                    $(t).html(e).modal("show")
                }
            })
        })

        $('.action-edit').on("click",function(e){
            e.stopPropagation();
            var t = $('.action-modal');
            $.ajax({
                url: $(this).data('href'),
                dataType: "html",
                success: function(e) {
                    $(t).html(e).modal("show")
                }
            })
        });

        // On Delete
        $('.action-delete').on("click", function(e){
            var btn = $(this);
            e.stopPropagation();
            Swal.fire({
                title: 'Anda yakin?',
                text: "Anda akan menghapus data ini!",
                icon: 'warning',
                showCancelButton: true,
                confirmButtonColor: '#3085d6',
                cancelButtonColor: '#d33',
                confirmButtonText: 'Ya, Hapus!'
            }).then((result) => {
                if (result.value) {
                    $.ajax({
                        url: btn.data('href'),
                        method: 'DELETE',
                        headers: {
                            'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
                        },
                        dataType: 'json',
                        success: function(res) {
                            if(res.status) {
                                Swal.fire({
                                    icon: 'success',
                                    title: 'Berhasil',
                                    text: res.message
                                }).then((result) => {
                                    btn.closest('li').fadeOut();
                                    $('.start-chat-area').removeClass('d-none');
                                    $('.active-chat').addClass('d-none');
                                })
                            } else {
                                Swal.fire({
                                    icon: 'error',
                                    title: 'Gagal',
                                    text: res.message
                                })
                            }
                        }
                    })
                }
            })
        });

        function markVideoAsWatched(id) {
            $.ajax({
                url: 'video/' + id,
                dataType: "json",
                success: function(data) {
                    console.log(data);
                }
            })
        }
    </script>
@endsection