routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return redirect('/login');
});

Auth::routes();

Route::get('/dashboard', 'HomeController@index')->name('dashboard');
Route::get('kelas/{kelas:slug}/home', 'HomeController@home')->name('home');

Route::group(['middleware' => 'auth'], function () {
    Route::resource('users', 'UserController');
    Route::resource('kelas.materi', 'MateriController')->parameters([
        'kelas' => 'kelas:slug',
    ]);
    Route::resource('kelas.video', 'VideoController')->parameters([
        'kelas' => 'kelas:slug',
    ]);
    Route::post('kelas/{kelas:slug}/task/{id}/submit', 'TaskController@submit')->name('task.submit');
    Route::resource('kelas.task', 'TaskController')->parameters([
        'kelas' => 'kelas:slug',
    ]);
    Route::get('kelas/{kelas:slug}/people', 'KelasController@people')->name('kelas.people');
    Route::get('kelas/{kelas:slug}/diskusi', 'KelasController@diskusi')->name('kelas.diskusi');
    Route::get('kelas/join/create', 'KelasController@cjoin')->name('join.create');
    Route::post('kelas/join', 'KelasController@join')->name('join.store');
    Route::resource('kelas', 'KelasController')->parameters([
        'kelas' => 'kelas:slug',
    ]);
    Route::get('kelas/{kelas:slug}/soal/{id}/essayshow', 'SoalController@essay')->name('soal.showEssay');
    Route::post('kelas/{kelas:slug}/soal/exam/answer', 'SoalController@storeAnswer')->name('soal.storeAnswer');
    Route::post('kelas/{kelas:slug}/soal/exam/finish', 'SoalController@examFinish')->name('soal.examFinish');
    Route::post('kelas/{kelas:slug}/soal/{id}/item', 'SoalController@storeItem')->name('soal.storeItem');
    Route::post('kelas/{kelas:slug}/soal/{id}/exam', 'SoalController@examStart')->name('soal.examStart');
    Route::resource('kelas.soal', 'SoalController')->parameters([
        'kelas' => 'kelas:slug',
    ]);
    Route::get('home/notifications', 'HomeController@loadMoreNotifications');
    Route::post('kelas/{kelas:slug}/home/feed', 'HomeController@feed')->name('home.feed');
    Route::post('kelas/{kelas:slug}/home/reply', 'HomeController@reply')->name('home.reply');

    Route::get('kelas/{kelas:slug}/activity', 'ReportController@activity')->name('report.activity');
    Route::post('kelas/{kelas:slug}/nilai', 'ReportController@saveNilai')->name('report.saveNilai');
    Route::get('kelas/{kelas:slug}/nilai', 'ReportController@nilai')->name('report.nilai');
    Route::get('kelas/{kelas:slug}/nilai/{id}', 'ReportController@nilaiDetail')->name('report.nilaiDetail');

    Route::get('setting', 'HomeController@setting')->name('home.setting');
    Route::post('setting', 'HomeController@updateSetting')->name('home.updateSetting');
    Route::post('password', 'HomeController@updatePassword')->name('home.updatePassword');
});

app/Soal.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Soal extends Model
{
    protected $guarded = ['id'];

    public function soal_item()
    {
        return $this->hasMany(SoalItem::class);
    }
}

app/Http/Controllers/SoalController.php
<?php

namespace App\Http\Controllers;

use App\Soal;
use App\SoalItem;
use App\Exam;
use App\ExamAnswer;
use App\Jobs\ProcessOnFinished;
use App\Kelas;
use App\Nilai;
use DB;
use Illuminate\Http\Request;

class SoalController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Kelas $kelas)
    {
        $data = Soal::where('kelas_id', '=', $kelas->id)->get();

        if(auth()->user()->hasRole('student')) {
            $type = request()->type ?? 'UTS';

            $exam_done_ids = Exam::where([
                'siswa_id' => auth()->user()->id,
                'state' => 'done'
            ])->pluck('soal_id');

            $data = Soal::where('kelas_id', '=', $kelas->id)->whereNotIn('id', $exam_done_ids)->where('name', $type)->first();

            if($data) {
                $data->exam_state = 'none';
                $data->timer_ori = $data->timer;
                $data->is_permitted = $type == 'QUIZ' || $type == 'UTS' || $type == 'ESSAY' ? true : $this->calculateNilai($kelas);

                $exist_exam = Exam::where([
                    'soal_id' => $data->id,
                    'siswa_id' => auth()->user()->id
                ])->first();

                if($exist_exam) {
                    $diff = strtotime($exist_exam->expired_at) - strtotime(date('Y-m-d H:i:s'));
                    $data->timer = $diff;
                    $data->exam_state = 'start';

                    if($diff <= 0) {
                        $exist_exam->state = 'done';
                        $exist_exam->save();
                        $data->timer = $diff;
                        $data->exam_state = 'done';
                    }
                }
            } else {
                $exist_exam = null;
            }
            // dd($data);
            return view('soal.student', compact('data', 'exist_exam', 'kelas'));
        }

        return view('soal.index', compact('data', 'kelas'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create(Kelas $kelas)
    {
        return view('soal.create', compact('kelas'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request, Kelas $kelas)
    {
        $input = $request->all();
        $input['timer'] = $input['timer']*60;

        if(request()->name == 'ESSAY') $input['size_choices'] = 1;

        $soal = Soal::create($input);

        activity()
            ->performedOn($soal)
            ->causedBy(auth()->user())
            ->withProperties(['kelas' => $kelas->id])
            ->log(':causer.name menambahkan soal :subject.name');

        flash('Berhasil menambahkan soal')->success();

        if(request()->name == 'ESSAY') return redirect()->route('soal.showEssay', [$kelas->slug, $soal->id]);

        return redirect()->route('kelas.soal.show', [$kelas->slug, $soal->id]);
    }

    public function storeItem(Request $request, Kelas $kelas, $id)
    {
        $item_data = $request->all();
        $items = [];
        $soal = Soal::find($id);

        if(array_key_exists('old', $item_data)) {
            foreach($item_data['old'] as $id_item => $item) {
                if($soal->name != 'ESSAY') {
                    $olds = [
                        'soal_id' => $id,
                        'nomor' => $item['nomor'],
                        'question' => $item['soal'],
                        'choices' => json_encode($item['choices']),
                        'kj' => $item['kj']
                    ];
                } else {
                    $olds = [
                        'soal_id' => $id,
                        'nomor' => $item['nomor'],
                        'question' => $item['soal'],
                        'choices' => json_encode([]),
                        'kj' => $item['kj']
                    ];
                }

                SoalItem::find($id_item)->update($olds);
            }
        }

        if(array_key_exists('item', $item_data)) {
            foreach($item_data['item'] as $key => $item) {
                if($soal->name != 'ESSAY') {
                    $items[] = [
                        'soal_id' => $id,
                        'nomor' => $item['nomor'],
                        'question' => $item['soal'],
                        'choices' => json_encode($item['choices']),
                        'kj' => $item['kj']
                    ];
                } else {
                    $items[] = [
                        'soal_id' => $id,
                        'nomor' => $item['nomor'],
                        'question' => $item['soal'],
                        'choices' => json_encode([]),
                        'kj' => $item['kj']
                    ];
                }
            }
        }

        if(count($items) > 0) {
            SoalItem::insert($items);
        }

        flash('Berhasil menyimpan butir soal')->success();

        return redirect()->route('kelas.soal.index', [$kelas->slug]);
    }

    public function storeAnswer(Request $request)
    {
        try {
            $input = $request->all();
            $input['siswa_id'] = auth()->user()->id;
            $input['soal_item_id'] = $input['id'];

            $soal_item = SoalItem::findOrFail($input['id']);
            $soal = Soal::find($input['soal_id']);

            $input['exam_id'] = Exam::where([
                'siswa_id' => auth()->user()->id,
                'soal_id' => $soal_item->soal_id
            ])->first()->id;

            if($soal->name != 'ESSAY'){
                if(array_key_exists('answer', $input)) {
                    if($input['answer'] == $soal_item->kj)
                        $input['is_true'] = true;
                    else
                        $input['is_true'] = false;
                } else {
                    $input['is_true'] = false;
                }
            }
            $input['is_true'] = true;

            $old_answer = ExamAnswer::where([
                'siswa_id' => auth()->user()->id,
                'soal_item_id' => $input['id'],
                'soal_id' => $input['soal_id']
            ])->first();

            if($old_answer) {
                $old_answer->update($input);
            } else {
                ExamAnswer::create($input);
            }

            return response()->json([
                'status' => true,
                'message' => 'Berhasil menyimpan jawaban'
            ]);
        } catch(\Exception $e) {
            dd($e);
            return response()->json([
                'status' => false,
                'message' => 'Gagal menyimpan jawaban'
            ]);
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show(Kelas $kelas, $id)
    {
        $data = Soal::find($id);
        return view('soal.show', compact('data', 'kelas'));
    }

    public function essay(Kelas $kelas, $id)
    {
        $data = Soal::find($id);
        return view('soal.essay', compact('data', 'kelas'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(Kelas $kelas, $id)
    {
        $data = Soal::find($id);
        return view('soal.edit', compact('data', 'kelas'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Kelas $kelas, $id)
    {
        $input = $request->all();
        $input['timer'] = $input['timer']*60;

        Soal::find($id)->update($input);

        flash('Berhasil mengedit soal')->success();

        return redirect()->route('kelas.soal.index', [$kelas->slug]);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(Kelas $kelas, $id)
    {
        try {
            Soal::find($id)->delete();

            return response()->json([
                'status' => true,
                'message' => 'Berhasil menghapus soal'
            ]);
        } catch(\Exception $e) {
            return response()->json([
                'status' => false,
                'message' => 'Gagal menghapus soal'
            ]);
        }
    }

    public function examStart(Kelas $kelas, $id)
    {
        try {
            $soal = Soal::findOrFail($id);

            $expired_at = strtotime(date('Y-m-d H:i:s')) + $soal->timer;
            $expired_at = date('Y-m-d H:i:s', $expired_at);

            $exam = Exam::create([
                'siswa_id' => auth()->user()->id,
                'soal_id' => $id,
                'expired_at' => $expired_at
            ]);

            activity()
                ->performedOn($soal)
                ->causedBy(auth()->user())
                ->withProperties(['kelas' => $kelas->id])
                ->log(':causer.name memulai timer ujian :subject.name');

            return response()->json([
                'status' => true,
                'message' => 'Berhasil memulai ujian',
                'exam_id' => $exam->id
            ]);
        } catch(\Exception $e) {
            return response()->json([
                'status' => false,
                'message' => 'Gagal memulai ujian'
            ]);
        }
    }

    public function examFinish(Request $request, Kelas $kelas)
    {
        try {
            DB::beginTransaction();

            $exam = Exam::findOrFail($request->id);
            $exam->update(['state' => 'done']);

resources/views/soal/create.blade.php
<div class="modal-dialog" role="document">
    {!! Form::open(['url' => route('kelas.soal.store', [$kelas->slug]), 'method' => 'post']) !!}
    <div class="modal-content">
        <div class="modal-header">
            <h4 class="modal-title" id="exampleModalLabel">Tambah Soal</h5>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
            </button>
        </div>
        <div class="modal-body">
            <input type="hidden" name="kelas_id" value="{{ $kelas->id }}">
            <div class="form-group">
                {!! Form::label('name', 'Soal') !!}
                {!! Form::select('name', ['UTS' => 'UTS', 'UAS' => 'UAS', 'QUIZ' => 'QUIZ', 'ESSAY' => 'ESSAY'], null, ['class' => 'form-control', 'required', 'oninvalid' => "this.setCustomValidity('Mohon diisi dengan lengkap')", 'oninput' => "this.setCustomValidity('')"]) !!}
            </div>
            <div class="form-group">
                {!! Form::label('size_item', 'Jumlah Butir Soal') !!}
                {!! Form::number('size_item', 1, ['class' => 'form-control', 'required', 'oninvalid' => "this.setCustomValidity('Mohon diisi dengan lengkap')", 'oninput' => "this.setCustomValidity('')"]) !!}
            </div>
            <div class="form-group" id="pil">
                {!! Form::label('size_choices', 'Jumlah Butir Pilihan Per Soal') !!}
                {!! Form::number('size_choices', 4, ['class' => 'form-control', 'required', 'oninvalid' => "this.setCustomValidity('Mohon diisi dengan lengkap')", 'oninput' => "this.setCustomValidity('')"]) !!}
            </div>
            <div class="form-group" id="time">
                {!! Form::label('timer', 'Waktu Pengerjaan (menit)') !!}
                {!! Form::number('timer', 90, ['class' => 'form-control', 'required', 'oninvalid' => "this.setCustomValidity('Mohon diisi dengan lengkap')", 'oninput' => "this.setCustomValidity('')"]) !!}
            </div>
            <div class="form-group">
                {!! Form::label('start_at', 'Tgl Mulai') !!}
                {!! Form::text('start_at', null, ['class' => 'form-control pickadate', 'required', 'oninvalid' => "this.setCustomValidity('Mohon diisi dengan lengkap')", 'oninput' => "this.setCustomValidity('')"]) !!}
            </div>
            <div class="form-group">
                {!! Form::label('due_at', 'Deadline') !!}
                {!! Form::text('due_at', null, ['class' => 'form-control pickadate', 'required', 'oninvalid' => "this.setCustomValidity('Mohon diisi dengan lengkap')", 'oninput' => "this.setCustomValidity('')"]) !!}
            </div>
        </div>
        <div class="modal-footer">
            <button type="submit" class="btn btn-primary">Simpan dan Tambah Butir Soal</button>
        </div>
    </div>
    {!! Form::close() !!}
</div>
<script>
$('.pickadate').pickadate({
    editable: true,
    format: 'yyyy-mm-dd'
});
</script>
<script>
    $(document).ready(function(){
        let pil = $('#pil')
        $('#name').on('change', function() {
            this.value == 'ESSAY' ? pil.remove() : pil.insertBefore("#time")
        })
    })
</script>

resources/views/soal/edit.blade.php
<div class="modal-dialog" role="document">
    {!! Form::open(['url' => route('kelas.soal.update', [$kelas->slug, $data->id]), 'method' => 'put']) !!}
    <div class="modal-content">
        <div class="modal-header">
            <h4 class="modal-title" id="exampleModalLabel">Edit Soal</h5>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
            </button>
        </div>
        <div class="modal-body">
            <div class="form-group">
                {!! Form::label('name', 'Soal') !!}
                {!! Form::select('name', ['UTS' => 'UTS', 'UAS' => 'UAS', 'QUIZ' => 'QUIZ'], $data->name, ['class' => 'form-control', 'required', 'oninvalid' => "this.setCustomValidity('Mohon diisi dengan lengkap')", 'oninput' => "this.setCustomValidity('')"]) !!}
            </div>
            <div class="form-group">
                {!! Form::label('size_item', 'Jumlah Butir Soal') !!}
                {!! Form::number('size_item', $data->size_item, ['class' => 'form-control', 'required', 'oninvalid' => "this.setCustomValidity('Mohon diisi dengan lengkap')", 'oninput' => "this.setCustomValidity('')"]) !!}
            </div>
            <div class="form-group">
                {!! Form::label('size_choices', 'Jumlah Butir Pilihan Per Soal') !!}
                {!! Form::number('size_choices', $data->size_choices, ['class' => 'form-control', 'required', 'oninvalid' => "this.setCustomValidity('Mohon diisi dengan lengkap')", 'oninput' => "this.setCustomValidity('')"]) !!}
            </div>
            <div class="form-group">
                {!! Form::label('timer', 'Waktu Pengerjaan (menit)') !!}
                {!! Form::number('timer', $data->timer/60, ['class' => 'form-control', 'required', 'oninvalid' => "this.setCustomValidity('Mohon diisi dengan lengkap')", 'oninput' => "this.setCustomValidity('')"]) !!}
            </div>
            <div class="form-group">
                {!! Form::label('start_at', 'Tgl Mulai') !!}
                {!! Form::text('start_at', $data->start_at, ['class' => 'form-control pickadate', 'required', 'oninvalid' => "this.setCustomValidity('Mohon diisi dengan lengkap')", 'oninput' => "this.setCustomValidity('')"]) !!}
            </div>
            <div class="form-group">
                {!! Form::label('due_at', 'Deadline') !!}
                {!! Form::text('due_at', $data->due_at, ['class' => 'form-control pickadate', 'required', 'oninvalid' => "this.setCustomValidity('Mohon diisi dengan lengkap')", 'oninput' => "this.setCustomValidity('')"]) !!}
            </div>
        </div>
        <div class="modal-footer">
            <button type="submit" class="btn btn-primary">Simpan</button>
        </div>
    </div>
    {!! Form::close() !!}
</div>
<script>
$('.pickadate').pickadate({
    editable: true,
    format: 'yyyy-mm-dd'
});
</script>

resources/views/soal/essay.blade.php
@extends('layouts.app')

@section('header')
    @include('kelas.partials.header')
@endsection

@section('content')
<div class="content-header row">
    <div class="content-header-left col-md-12 col-12 mb-2">
        <div class="row breadcrumbs-top">
            <div class="col-12">
                <h2 class="content-header-title d-flex justify-content-center mb-0">Data Soal {{ $data->name ?? '' }}</h2>
            </div>
        </div>
    </div>
</div>
<div class="content-body">
    <!-- Data list view starts -->
    {!! Form::open(['url' => route('soal.storeItem', [$kelas->slug, $data->id]), 'method' => 'post']) !!}
    <div class="card collapse-icon accordion-icon-rotate">
        <div class="card-header">
            <h4 class="card-title">Butir Soal</h4>
        </div>
        <div class="card-body">
            <div class="accordion" id="accordionExample" data-toggle-hover="true">
                @for ($i = 0; $i < $data->size_item; $i++)
                    @php
                        $old_item = \App\SoalItem::where('nomor', $i+1)
                                                ->where('soal_id', $data->id)
                                                ->first();
                    @endphp
                    @if ($old_item)
                    <div class="collapse-margin">
                        {!! Form::hidden('old['.$old_item->id.'][nomor]', $old_item->nomor) !!}
                        <div class="card-header collapsed" id="heading_{{ $i }}" data-toggle="collapse" role="button" data-target="#collapse_{{ $i }}" aria-expanded="false" aria-controls="collapseOne">
                            <div class="lead collapse-title" style="width: 95%">
                                <fieldset class="form-label-group form-group position-relative has-icon-left">
                                    {!! Form::text('old['.$old_item->id.'][soal]', $old_item->question, ['id' => 'item_'.$i, 'class' => 'form-control', 'placeholder' => 'Tulis Pertanyaan', 'required']) !!}
                                    <div class="form-control-position">{{ $old_item->nomor }}.</div>
                                    {!! Form::label('item_'.$i, 'Tulis Pertanyaan') !!}
                                </fieldset>
                            </div>
                        </div>
                        <div id="collapse_{{ $i }}" class="collapse" aria-labelledby="heading_{{ $i }}" data-parent="#accordionExample" style="">
                            <div class="card-body">
                                @for ($j = 0; $j < $data->size_choices; $j++)
                                <fieldset class="mb-1">
                                    <div class="input-group">
                                        {!! Form::text('old['.$old_item->id.'][kj]', $old_item->kj, ['class' => 'form-control', 'placeholder' => 'Tulis Jawaban', 'required']) !!}
                                    </div>
                                </fieldset>
                                @endfor
                            </div>
                        </div>
                    </div>
                    @else
                    <div class="collapse-margin">
                        {!! Form::hidden('item['.$i.'][nomor]', $i+1) !!}
                        <div class="card-header collapsed" id="heading_{{ $i }}" data-toggle="collapse" role="button" data-target="#collapse_{{ $i }}" aria-expanded="false" aria-controls="collapseOne">
                            <div class="lead collapse-title" style="width: 95%">
                                <fieldset class="form-label-group form-group position-relative has-icon-left">
                                    {!! Form::text('item['.$i.'][soal]', null, ['id' => 'item_'.$i, 'class' => 'form-control', 'placeholder' => 'Tulis Pertanyaan', 'required']) !!}
                                    <div class="form-control-position">{{$i+1}}.</div>
                                    {!! Form::label('item_'.$i, 'Tulis Pertanyaan') !!}
                                </fieldset>
                            </div>
                        </div>
                        <div id="collapse_{{ $i }}" class="collapse" aria-labelledby="heading_{{ $i }}" data-parent="#accordionExample" style="">
                            <div class="card-body">
                                @for ($j = 0; $j < $data->size_choices; $j++)
                                <fieldset class="mb-1">
                                    <div class="input-group">
                                        {!! Form::text('item['.$i.'][kj]', null, ['class' => 'form-control', 'placeholder' => 'Tulis Jawaban', 'required']) !!}
                                    </div>
                                </fieldset>
                                @endfor
                            </div>
                        </div>
                    </div>
                    @endif
                @endfor
            </div>
        </div>
    </div>
    <button type="submit" class="btn btn-primary float-right">Simpan</button>
    {!! Form::close() !!}
    <!-- Data list view end -->

    <div class="modal fade action-modal" id="xlarge" tabindex="-1" role="dialog" aria-labelledby="myModalLabel16" aria-hidden="true"></div>

</div>
@endsection

@section('js')

@endsection

resources/views/soal/index.blade.php
@extends('layouts.app')

@section('header')
    @include('kelas.partials.header')
@endsection

@section('content')
<div class="content-header row">
    <div class="content-header-left col-md-12 col-12 mb-2">
        <div class="row breadcrumbs-top">
            <div class="col-12">
                <h2 class="content-header-title d-flex justify-content-center mb-0">Data Soal</h2>
            </div>
        </div>
    </div>
</div>
<div class="content-body">
    <!-- Data list view starts -->
    <section id="basic-datatable">
        <div class="row">
            <div class="col-12">
                <div class="card">
                    <div class="card-header">
                        <button class="btn btn-outline-primary btn-modal" data-href="{{ route('kelas.soal.create', [$kelas->slug]) }}"><i class='feather icon-plus'></i> Tambah</button>
                    </div>
                    <div class="card-content">
                        <div class="card-body card-dashboard">
                            <div class="table-responsive">
                                <table class="table table-striped datatable">
                                    <thead>
                                        <tr>
                                            <th>Soal</th>
                                            <th>Waktu</th>
                                            <th>Tgl Mulai</th>
                                            <th>Tgl Deadline</th>
                                            <th>Tindakan</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        @foreach ($data as $value)
                                            <tr>
                                                <td>{{ $value->name ?? '' }}</td>
                                                <td>{{ $value->timer/60 }} menit</td>
                                                <td>{{ date('d/m/Y', strtotime($value->start_at)) }}</td>
                                                <td>{{ date('d/m/Y', strtotime($value->due_at)) }}</td>
                                                <td>
                                                    @if($value->name == 'ESSAY')
                                                    <a href="{{ route('soal.showEssay', [$kelas->slug, $value->id]) }}"><i class="feather icon-eye" title="Lihat Soal"></i></a>
                                                    @else
                                                    <a href="{{ route('kelas.soal.show', [$kelas->slug, $value->id]) }}"><i class="feather icon-eye" title="Lihat Soal"></i></a>
                                                    @endif
                                                    <span class="btn-modal" style="cursor: pointer;" data-href="{{ route('kelas.soal.edit', [$kelas->slug, $value->id]) }}"><i class="feather icon-edit" title="Edit"></i></span>
                                                    <span class="action-delete" style="cursor: pointer;" data-href="{{ route('kelas.soal.destroy', [$kelas->slug, $value->id]) }}"><i class="feather icon-trash" title="Delete"></i></span>
                                                </td>
                                            </tr>
                                        @endforeach
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- Data list view end -->

    <div class="modal fade action-modal" id="xlarge" tabindex="-1" role="dialog" aria-labelledby="myModalLabel16" aria-hidden="true"></div>

</div>
@endsection

@section('js')
    <script>
        $('.datatable').DataTable();

        $('.datatable').on('click', '.btn-modal', function(e){
            var t = $('.action-modal');
            $.ajax({
                url: $(this).data('href'),
                dataType: "html",
                success: function(e) {
                    $(t).html(e).modal("show")
                }
            })
        })

        $('.datatable').on('click', '.action-delete', function(e){
            var btn = $(this);
            e.stopPropagation();
            Swal.fire({
                title: 'Anda yakin?',
                text: "Anda akan menghapus data ini!",
                icon: 'warning',
                showCancelButton: true,
                confirmButtonColor: '#3085d6',
                cancelButtonColor: '#d33',
                confirmButtonText: 'Ya, Hapus!'
            }).then((result) => {
                if (result.value) {
                    $.ajax({
                        url: btn.data('href'),
                        method: 'DELETE',
                        headers: {
                            'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
                        },
                        dataType: 'json',
                        success: function(res) {
                            if(res.status) {
                                Swal.fire({
                                    icon: 'success',
                                    title: 'Berhasil',
                                    text: res.message
                                }).then((result) => {
                                    btn.closest('td').parent('tr').fadeOut();
                                })
                            } else {
                                Swal.fire({
                                    icon: 'error',
                                    title: 'Gagal',
                                    text: res.message
                                })
                            }
                        }
                    })
                }
            })
        });
    </script>
@endsection