routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return redirect('/login');
});

Auth::routes();

Route::get('/dashboard', 'HomeController@index')->name('dashboard');
Route::get('kelas/{kelas:slug}/home', 'HomeController@home')->name('home');

Route::group(['middleware' => 'auth'], function () {
    Route::resource('users', 'UserController');
    Route::resource('kelas.materi', 'MateriController')->parameters([
        'kelas' => 'kelas:slug',
    ]);
    Route::resource('kelas.video', 'VideoController')->parameters([
        'kelas' => 'kelas:slug',
    ]);
    Route::post('kelas/{kelas:slug}/task/{id}/submit', 'TaskController@submit')->name('task.submit');
    Route::resource('kelas.task', 'TaskController')->parameters([
        'kelas' => 'kelas:slug',
    ]);
    Route::get('kelas/{kelas:slug}/people', 'KelasController@people')->name('kelas.people');
    Route::get('kelas/{kelas:slug}/diskusi', 'KelasController@diskusi')->name('kelas.diskusi');
    Route::get('kelas/join/create', 'KelasController@cjoin')->name('join.create');
    Route::post('kelas/join', 'KelasController@join')->name('join.store');
    Route::resource('kelas', 'KelasController')->parameters([
        'kelas' => 'kelas:slug',
    ]);
    Route::get('kelas/{kelas:slug}/soal/{id}/essayshow', 'SoalController@essay')->name('soal.showEssay');
    Route::post('kelas/{kelas:slug}/soal/exam/answer', 'SoalController@storeAnswer')->name('soal.storeAnswer');
    Route::post('kelas/{kelas:slug}/soal/exam/finish', 'SoalController@examFinish')->name('soal.examFinish');
    Route::post('kelas/{kelas:slug}/soal/{id}/item', 'SoalController@storeItem')->name('soal.storeItem');
    Route::post('kelas/{kelas:slug}/soal/{id}/exam', 'SoalController@examStart')->name('soal.examStart');
    Route::resource('kelas.soal', 'SoalController')->parameters([
        'kelas' => 'kelas:slug',
    ]);
    Route::get('home/notifications', 'HomeController@loadMoreNotifications');
    Route::post('kelas/{kelas:slug}/home/feed', 'HomeController@feed')->name('home.feed');
    Route::post('kelas/{kelas:slug}/home/reply', 'HomeController@reply')->name('home.reply');

    Route::get('kelas/{kelas:slug}/activity', 'ReportController@activity')->name('report.activity');
    Route::post('kelas/{kelas:slug}/nilai', 'ReportController@saveNilai')->name('report.saveNilai');
    Route::get('kelas/{kelas:slug}/nilai', 'ReportController@nilai')->name('report.nilai');
    Route::get('kelas/{kelas:slug}/nilai/{id}', 'ReportController@nilaiDetail')->name('report.nilaiDetail');

    Route::get('setting', 'HomeController@setting')->name('home.setting');
    Route::post('setting', 'HomeController@updateSetting')->name('home.updateSetting');
    Route::post('password', 'HomeController@updatePassword')->name('home.updatePassword');
});

app/Materi.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Materi extends Model
{
    protected $guarded = ['id'];

    public function kelas()
    {
        return $this->belongsTo(Kelas::class);
    }
}

app/Http/Controllers/MateriController.php
<?php

namespace App\Http\Controllers;

use App\Kelas;
use App\Materi;

use Illuminate\Http\Request;

class MateriController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Kelas $kelas)
    {
        $data = Materi::where('kelas_id', '=', $kelas->id)->get();
        return view('materi.index', compact('data', 'kelas'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create(Kelas $kelas)
    {
        return view('materi.create', compact('kelas'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request, Kelas $kelas)
    {
        $input = $request->all();

        if ($request->hasFile('file')) {
            $input['file'] = time().'_'.request()->file->getClientOriginalName();
            
            request()->file->move(public_path('uploads/file/'), $input['file']);
        }
        
        $data = Materi::create($input);

        activity()
            ->performedOn($data)
            ->causedBy(auth()->user())
            ->withProperties(['kelas' => $kelas->id])
            ->log(':causer.name menambahkan materi :subject.name');

        flash('Berhasil menambahkan materi')->success();

        return redirect()->route('kelas.materi.index', [$kelas->slug]);
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show(Kelas $kelas, $id)
    {
        $data = Materi::find($id);

        activity()
            ->performedOn($data)
            ->causedBy(auth()->user())
            ->withProperties(['kelas' => $kelas->id])
            ->log(':causer.name mendownload materi :subject.name');

        return response()->json($data);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(Kelas $kelas, $id)
    {
        $data = Materi::find($id);
        return view('materi.edit', compact('data', 'kelas'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Kelas $kelas, $id)
    {
        $input = $request->all();

        if ($request->hasFile('file')) {
            $input['file'] = time().'_'.request()->file->getClientOriginalName();
            
            request()->file->move(public_path('uploads/file/'), $input['file']);
        }
        
        Materi::find($id)->update($input);

        flash('Berhasil mengedit materi')->success();

        return redirect()->route('kelas.materi.index', [$kelas->slug]);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(Kelas $kelas, $id)
    {
        try {
            Materi::find($id)->delete();

            return response()->json([
                'status' => true,
                'message' => 'Berhasil menghapus materi'
            ]);
        } catch(\Exception $e) {
            return response()->json([
                'status' => false,
                'message' => 'Gagal menghapus materi'
            ]);
        }
    }
}

resources/views/materi/create.blade.php
<div class="modal-dialog" role="document">
    {!! Form::open(['url' => route('kelas.materi.store', [$kelas->slug]), 'method' => 'post', 'files' => true]) !!}
    <div class="modal-content">
        <div class="modal-header">
            <h4 class="modal-title" id="exampleModalLabel">Tambah Materi {{ $kelas->name }}</h5>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
            </button>
        </div>
        <div class="modal-body">
            <input type="hidden" name="kelas_id" value="{{ $kelas->id }}">
            <div class="form-group">
                {!! Form::label('name', 'Judul') !!}
                {!! Form::text('name', null, ['class' => 'form-control', 'required', 'oninvalid' => "this.setCustomValidity('Mohon diisi dengan lengkap')", 'oninput' => "this.setCustomValidity('')"]) !!}
            </div>
            <div class="form-group">
                {!! Form::label('description', 'Deskripsi') !!}
                {!! Form::textarea('description', null, ['class' => 'form-control', 'required', 'oninvalid' => "this.setCustomValidity('Mohon diisi dengan lengkap')", 'oninput' => "this.setCustomValidity('')"]) !!}
            </div>
            <div class="form-group">
                {!! Form::label('file', 'File') !!}
                {!! Form::file('file', null, ['class' => 'form-control-file', 'required', 'oninvalid' => "this.setCustomValidity('Mohon diisi dengan lengkap')", 'oninput' => "this.setCustomValidity('')"]) !!}
            </div>
        </div>
        <div class="modal-footer">
            <button type="submit" class="btn btn-primary">Simpan</button>
        </div>
    </div>
    {!! Form::close() !!}
</div>

resources/views/materi/edit.blade.php
<div class="modal-dialog" role="document">
    {!! Form::open(['url' => route('kelas.materi.update', [$kelas->slug, $data->id]), 'method' => 'post', 'files' => true]) !!}
    @method('PUT')
    <div class="modal-content">
        <div class="modal-header">
            <h4 class="modal-title" id="exampleModalLabel">Edit Materi</h5>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
            </button>
        </div>
        <div class="modal-body">
            <div class="form-group">
                {!! Form::label('name', 'Judul') !!}
                {!! Form::text('name', $data->name, ['class' => 'form-control', 'required', 'oninvalid' => "this.setCustomValidity('Mohon diisi dengan lengkap')", 'oninput' => "this.setCustomValidity('')"]) !!}
            </div>
            <div class="form-group">
                {!! Form::label('description', 'Deskripsi') !!}
                {!! Form::textarea('description', $data->description, ['class' => 'form-control', 'required', 'oninvalid' => "this.setCustomValidity('Mohon diisi dengan lengkap')", 'oninput' => "this.setCustomValidity('')"]) !!}
            </div>
            <div class="form-group">
                {!! Form::label('file', 'File') !!}
                {!! Form::file('file', null, ['class' => 'form-control-file', 'required', 'oninvalid' => "this.setCustomValidity('Mohon diisi dengan lengkap')", 'oninput' => "this.setCustomValidity('')"]) !!}
            </div>
        </div>
        <div class="modal-footer">
            <button type="submit" class="btn btn-primary">Simpan</button>
        </div>
    </div>
    {!! Form::close() !!}
</div>

resources/views/materi/index.blade.php
@extends('layouts.app')

@section('header')
    @include('kelas.partials.header')
@endsection

@section('content')
<div class="content-header row">
    <div class="content-header-left col-md-12 col-12 mb-2">
        <div class="row breadcrumbs-top">
            <div class="col-12">
                <h2 class="content-header-title d-flex justify-content-center mb-0">Timeline Materi</h2>
            </div>
        </div>
    </div>
</div>
<div class="content-body">
    <input type="hidden" id="kelas_slug" value="{{ $kelas->slug }}">
    <!-- Data list view starts -->
    <section id="data-thumb-view" class="data-thumb-view-header">
        <!-- dataTable starts -->
        <div class="table-responsive">
            <table class="table data-thumb-view">
                <thead>
                    <tr>
                        <th></th>
                        <th>Judul</th>
                        <th>Deskripsi</th>
                        <th>Tgl</th>
                        <th>File</th>
                        @if (!auth()->user()->hasRole('student'))
                            <th>Tindakan</th>
                        @endif
                    </tr>
                </thead>
                <tbody>
                    @foreach ($data as $value)
                        <tr>
                            <td></td>
                            <td>{{ $value->name ?? '' }}</td>
                            <td>{{ $value->description ?? '' }}</td>
                            <td>{{ date('Y/m/d', strtotime($value->created_at)) }}</td>
                            <td>
                                <div class="chip chip-success">
                                    <div class="chip-body">
                                        <div class="chip-text"><span class="action-show" data-link="{{ asset('uploads/file/'.$value->file) }}" data-href="{{ route('kelas.materi.show', [$kelas->slug, $value->id]) }}">Download</span></div>
                                    </div>
                                </div>
                            </td>
                            @if (!auth()->user()->hasRole('student'))
                            <td>
                                <span class="action-edit" data-href="{{ route('kelas.materi.edit', [$kelas->slug, $value->id]) }}"><i class="feather icon-edit" title="Edit"></i></span>
                                <span class="action-delete" data-href="{{ route('kelas.materi.destroy', [$kelas->slug, $value->id]) }}"><i class="feather icon-trash" title="Delete"></i></span>
                            </td>
                            @endif
                        </tr>
                    @endforeach
                </tbody>
            </table>
        </div>
        <!-- dataTable ends -->
    </section>
    <!-- Data list view end -->

    <div class="modal fade action-modal" id="xlarge" tabindex="-1" role="dialog" aria-labelledby="myModalLabel16" aria-hidden="true"></div>

</div>
@endsection

@section('js')
    <script>
        $(document).ready(function() {
            "use strict"
            // init thumb view datatable
            var dataThumbView = $(".data-thumb-view").DataTable({
                responsive: false,
                columnDefs: [
                {
                    orderable: true,
                    targets: 0,
                    checkboxes: { selectRow: true }
                }
                ],
                dom:
                '<"top"<"actions action-btns"B><"action-filters"lf>><"clear">rt<"bottom"<"actions">p>',
                oLanguage: {
                sLengthMenu: "_MENU_",
                sSearch: ""
                },
                aLengthMenu: [[4, 10, 15, 20], [4, 10, 15, 20]],
                select: {
                style: "multi"
                },
                order: [[3, "asc"]],
                bInfo: false,
                pageLength: 20,
                buttons: [
                    @if(!auth()->user()->hasRole('student'))
                    {
                        text: "<i class='feather icon-plus'></i> Tambah",
                        action: function() {
                            $(this).removeClass("btn-secondary")
                            
                            var t = $('.action-modal');
                            const slug = $('#kelas_slug').val()
                            let url = "{{ route('kelas.materi.create', ":slug") }}"
                            url = url.replace(':slug', slug)
                            $.ajax({
                                url,
                                dataType: "html",
                                success: function(e) {
                                    $(t).html(e).modal("show")
                                }
                            })
                        },
                        className: "btn-outline-primary"
                    }
                    @endif
                ],
                initComplete: function(settings, json) {
                $(".dt-buttons .btn").removeClass("btn-secondary")
                }
            })

            dataThumbView.on('draw.dt', function(){
                setTimeout(function(){
                if (navigator.userAgent.indexOf("Mac OS X") != -1) {
                    $(".dt-checkboxes-cell input, .dt-checkboxes").addClass("mac-checkbox")
                }
                }, 50);
            });

            // To append actions dropdown before add new button
            var actionDropdown = $(".actions-dropodown")
            actionDropdown.insertBefore($(".top .actions .dt-buttons"))


            // Scrollbar
            if ($(".data-items").length > 0) {
                new PerfectScrollbar(".data-items", { wheelPropagation: false })
            }

            // Close sidebar
            $(".hide-data-sidebar, .cancel-data-btn, .overlay-bg").on("click", function() {
                $(".add-new-data").removeClass("show")
                $(".overlay-bg").removeClass("show")
                $("#data-name, #data-price").val("")
                $("#data-category, #data-status").prop("selectedIndex", 0)
            })

            // On Edit
            $('.action-edit').on("click",function(e){
                e.stopPropagation();
                var t = $('.action-modal');
                $.ajax({
                    url: $(this).data('href'),
                    dataType: "html",
                    success: function(e) {
                        $(t).html(e).modal("show")
                    }
                })
            });

            // On Stok
            $('.action-show').on("click",function(e){
                e.stopPropagation();
                const link = $(this).data('link');
                $.ajax({
                    url: $(this).data('href'),
                    dataType: "json",
                    success: function(data) {
                        window.open(link,'_blank');
                    }
                })
            });

            // On Delete
            $('.action-delete').on("click", function(e){
                var btn = $(this);
                e.stopPropagation();
                Swal.fire({
                    title: 'Anda yakin?',
                    text: "Anda akan menghapus data ini!",
                    icon: 'warning',
                    showCancelButton: true,
                    confirmButtonColor: '#3085d6',
                    cancelButtonColor: '#d33',
                    confirmButtonText: 'Ya, Hapus!'
                }).then((result) => {
                    if (result.value) {
                        $.ajax({
                            url: btn.data('href'),
                            method: 'DELETE',
                            headers: {
                                'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
                            },
                            dataType: 'json',
                            success: function(res) {
                                if(res.status) {
                                    Swal.fire({
                                        icon: 'success',
                                        title: 'Berhasil',
                                        text: res.message
                                    }).then((result) => {
                                        btn.closest('td').parent('tr').fadeOut();
                                    })
                                } else {
                                    Swal.fire({
                                        icon: 'error',
                                        title: 'Gagal',
                                        text: res.message
                                    })
                                }
                            }
                        })
                    }
                })
            });

            // dropzone init
            Dropzone.options.dataListUpload = {
                complete: function(files) {
                var _this = this
                // checks files in class dropzone and remove that files
                $(".hide-data-sidebar, .cancel-data-btn, .actions .dt-buttons").on(
                    "click",
                    function() {
                    $(".dropzone")[0].dropzone.files.forEach(function(file) {
                        file.previewElement.remove()
                    })
                    $(".dropzone").removeClass("dz-started")
                    }
                )
                }
            }
            Dropzone.options.dataListUpload.complete()

            // mac chrome checkbox fix
            if (navigator.userAgent.indexOf("Mac OS X") != -1) {
                $(".dt-checkboxes-cell input, .dt-checkboxes").addClass("mac-checkbox")
            }
        })
    </script>
@endsection